// Generated by scripts/parity/generate-model-cards.mjs. Do not edit manually.

import type { RawModelCardRecord } from './card';

export const MODEL_CARD_RECORDS = [
    {
        kind: 'embedding',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/embedding/_dashscope/_models/multimodal-embedding-v1.yaml',
        config: {
            name: 'multimodal-embedding-v1',
            label: 'Multimodal Embedding v1',
            status: 'active',
            input_types: ['text/plain', 'image/jpeg', 'image/png', 'image/bmp'],
            output_types: ['application/x-embedding'],
            context_size: 512,
            dimensions: 1024,
        },
    },
    {
        kind: 'embedding',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/embedding/_dashscope/_models/qwen2.5-vl-embedding.yaml',
        config: {
            name: 'qwen2.5-vl-embedding',
            label: 'Qwen2.5 VL Embedding',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/webp',
                'image/bmp',
                'image/tiff',
                'video/mp4',
            ],
            output_types: ['application/x-embedding'],
            context_size: 32000,
            dimensions: 1024,
            supported_dimensions: [2048, 1024, 768, 512],
        },
    },
    {
        kind: 'embedding',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/embedding/_dashscope/_models/qwen3-vl-embedding.yaml',
        config: {
            name: 'qwen3-vl-embedding',
            label: 'Qwen3 VL Embedding',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/webp',
                'image/bmp',
                'image/tiff',
                'video/mp4',
            ],
            output_types: ['application/x-embedding'],
            context_size: 32000,
            dimensions: 2560,
            supported_dimensions: [2560, 2048, 1536, 1024, 768, 512, 256],
        },
    },
    {
        kind: 'embedding',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/embedding/_dashscope/_models/text-embedding-v3.yaml',
        config: {
            name: 'text-embedding-v3',
            label: 'Text Embedding v3',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['application/x-embedding'],
            context_size: 8192,
            dimensions: 1024,
            supported_dimensions: [1024, 768, 512, 256, 128, 64],
        },
    },
    {
        kind: 'embedding',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/embedding/_dashscope/_models/text-embedding-v4.yaml',
        config: {
            name: 'text-embedding-v4',
            label: 'Text Embedding v4',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['application/x-embedding'],
            context_size: 8192,
            dimensions: 1024,
            supported_dimensions: [2048, 1536, 1024, 768, 512, 256, 128, 64],
        },
    },
    {
        kind: 'embedding',
        provider: 'dashscope',
        sourcePath:
            'src/agentscope/embedding/_dashscope/_models/tongyi-embedding-vision-flash.yaml',
        config: {
            name: 'tongyi-embedding-vision-flash',
            label: 'Tongyi Embedding Vision Flash',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/webp',
                'image/bmp',
                'image/tiff',
                'video/mp4',
                'video/mpeg',
            ],
            output_types: ['application/x-embedding'],
            context_size: 1024,
            dimensions: 768,
            supported_dimensions: [768, 512, 256, 128, 64],
        },
    },
    {
        kind: 'embedding',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/embedding/_dashscope/_models/tongyi-embedding-vision-plus.yaml',
        config: {
            name: 'tongyi-embedding-vision-plus',
            label: 'Tongyi Embedding Vision Plus',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/webp',
                'image/bmp',
                'image/tiff',
                'video/mp4',
                'video/mpeg',
            ],
            output_types: ['application/x-embedding'],
            context_size: 1024,
            dimensions: 1152,
            supported_dimensions: [1152, 1024, 512, 256, 128, 64],
        },
    },
    {
        kind: 'embedding',
        provider: 'gemini',
        sourcePath: 'src/agentscope/embedding/_gemini/_models/gemini-embedding-001.yaml',
        config: {
            name: 'gemini-embedding-001',
            label: 'Gemini Embedding 001',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['application/x-embedding'],
            context_size: 2048,
            dimensions: 3072,
            supported_dimensions: [3072, 1536, 768, 512, 256, 128],
        },
    },
    {
        kind: 'embedding',
        provider: 'gemini',
        sourcePath: 'src/agentscope/embedding/_gemini/_models/gemini-embedding-2.yaml',
        config: {
            name: 'gemini-embedding-2',
            label: 'Gemini Embedding 2',
            status: 'active',
            input_types: [
                'text/plain',
                'image/png',
                'image/jpeg',
                'video/mp4',
                'audio/mpeg',
                'audio/wav',
                'application/pdf',
            ],
            output_types: ['application/x-embedding'],
            context_size: 8192,
            dimensions: 3072,
            supported_dimensions: [3072, 1536, 768],
        },
    },
    {
        kind: 'embedding',
        provider: 'openai',
        sourcePath: 'src/agentscope/embedding/_openai/_models/text-embedding-3-large.yaml',
        config: {
            name: 'text-embedding-3-large',
            label: 'Text Embedding 3 Large',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['application/x-embedding'],
            context_size: 8191,
            dimensions: 3072,
            supported_dimensions: [3072, 1536, 1024, 768, 512, 256],
        },
    },
    {
        kind: 'embedding',
        provider: 'openai',
        sourcePath: 'src/agentscope/embedding/_openai/_models/text-embedding-3-small.yaml',
        config: {
            name: 'text-embedding-3-small',
            label: 'Text Embedding 3 Small',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['application/x-embedding'],
            context_size: 8191,
            dimensions: 1536,
            supported_dimensions: [1536, 1024, 768, 512, 256],
        },
    },
    {
        kind: 'chat',
        provider: 'anthropic',
        sourcePath: 'src/agentscope/model/_anthropic/_models/claude-fable-5.yaml',
        config: {
            name: 'claude-fable-5',
            label: 'Claude Fable 5',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                thinking_budget: {
                    hidden: true,
                },
                thinking_mode: {
                    default: 'adaptive',
                    anyOf: [
                        {
                            enum: ['adaptive'],
                            type: 'string',
                        },
                        {
                            type: 'null',
                        },
                    ],
                },
                thinking_display: {
                    default: 'summarized',
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'anthropic',
        sourcePath: 'src/agentscope/model/_anthropic/_models/claude-haiku-4-5.yaml',
        config: {
            name: 'claude-haiku-4-5',
            label: 'Claude Haiku 4.5',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 200000,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
                thinking_mode: {
                    hidden: true,
                },
                thinking_display: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'anthropic',
        sourcePath: 'src/agentscope/model/_anthropic/_models/claude-opus-4-5.yaml',
        config: {
            name: 'claude-opus-4-5',
            label: 'Claude Opus 4.5',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 200000,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
                thinking_mode: {
                    hidden: true,
                },
                thinking_display: {
                    hidden: true,
                },
                reasoning_effort: {
                    anyOf: [
                        {
                            enum: ['low', 'medium', 'high'],
                            type: 'string',
                        },
                        {
                            type: 'null',
                        },
                    ],
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'anthropic',
        sourcePath: 'src/agentscope/model/_anthropic/_models/claude-opus-4-6.yaml',
        config: {
            name: 'claude-opus-4-6',
            label: 'Claude Opus 4.6',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                thinking_mode: {
                    default: 'adaptive',
                    anyOf: [
                        {
                            enum: ['adaptive', 'enabled', 'disabled'],
                            type: 'string',
                        },
                        {
                            type: 'null',
                        },
                    ],
                },
                reasoning_effort: {
                    anyOf: [
                        {
                            enum: ['low', 'medium', 'high', 'max'],
                            type: 'string',
                        },
                        {
                            type: 'null',
                        },
                    ],
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'anthropic',
        sourcePath: 'src/agentscope/model/_anthropic/_models/claude-opus-4-7.yaml',
        config: {
            name: 'claude-opus-4-7',
            label: 'Claude Opus 4.7',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                thinking_budget: {
                    hidden: true,
                },
                thinking_mode: {
                    default: 'adaptive',
                    anyOf: [
                        {
                            enum: ['adaptive', 'disabled'],
                            type: 'string',
                        },
                        {
                            type: 'null',
                        },
                    ],
                },
                thinking_display: {
                    default: 'summarized',
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'anthropic',
        sourcePath: 'src/agentscope/model/_anthropic/_models/claude-opus-4-8.yaml',
        config: {
            name: 'claude-opus-4-8',
            label: 'Claude Opus 4.8',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                thinking_budget: {
                    hidden: true,
                },
                thinking_mode: {
                    default: 'adaptive',
                    anyOf: [
                        {
                            enum: ['adaptive', 'disabled'],
                            type: 'string',
                        },
                        {
                            type: 'null',
                        },
                    ],
                },
                thinking_display: {
                    default: 'summarized',
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'anthropic',
        sourcePath: 'src/agentscope/model/_anthropic/_models/claude-opus-5.yaml',
        config: {
            name: 'claude-opus-5',
            label: 'Claude Opus 5',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                thinking_budget: {
                    hidden: true,
                },
                thinking_mode: {
                    default: 'adaptive',
                    anyOf: [
                        {
                            enum: ['adaptive', 'disabled'],
                            type: 'string',
                        },
                        {
                            type: 'null',
                        },
                    ],
                },
                thinking_display: {
                    default: 'summarized',
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'anthropic',
        sourcePath: 'src/agentscope/model/_anthropic/_models/claude-sonnet-4-5.yaml',
        config: {
            name: 'claude-sonnet-4-5',
            label: 'Claude Sonnet 4.5',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 200000,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
                thinking_mode: {
                    hidden: true,
                },
                thinking_display: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'anthropic',
        sourcePath: 'src/agentscope/model/_anthropic/_models/claude-sonnet-4-6.yaml',
        config: {
            name: 'claude-sonnet-4-6',
            label: 'Claude Sonnet 4.6',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                thinking_mode: {
                    default: 'adaptive',
                    anyOf: [
                        {
                            enum: ['adaptive', 'enabled', 'disabled'],
                            type: 'string',
                        },
                        {
                            type: 'null',
                        },
                    ],
                },
                reasoning_effort: {
                    anyOf: [
                        {
                            enum: ['low', 'medium', 'high', 'max'],
                            type: 'string',
                        },
                        {
                            type: 'null',
                        },
                    ],
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'anthropic',
        sourcePath: 'src/agentscope/model/_anthropic/_models/claude-sonnet-5.yaml',
        config: {
            name: 'claude-sonnet-5',
            label: 'Claude Sonnet 5',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                thinking_budget: {
                    hidden: true,
                },
                thinking_mode: {
                    default: 'adaptive',
                    anyOf: [
                        {
                            enum: ['adaptive', 'disabled'],
                            type: 'string',
                        },
                        {
                            type: 'null',
                        },
                    ],
                },
                thinking_display: {
                    default: 'summarized',
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/deepseek-v4-pro.yaml',
        config: {
            name: 'deepseek-v4-pro',
            label: 'DeepSeek V4 Pro',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 384000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 384000,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/glm-5.2.yaml',
        config: {
            name: 'glm-5.2',
            label: 'GLM 5.2',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen-flash.yaml',
        config: {
            name: 'qwen-flash',
            label: 'Qwen-Flash',
            status: 'active',
            input_types: ['text/plain', 'application/x-thinking'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 32768,
            parameter_overrides: {
                max_tokens: {
                    maximum: 32768,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen-long.yaml',
        config: {
            name: 'qwen-long',
            label: 'Qwen Long',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain'],
            context_size: 10000000,
            output_size: 8192,
            parameter_overrides: {
                max_tokens: {
                    maximum: 8192,
                },
                thinking_enable: {
                    hidden: true,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen-plus.yaml',
        config: {
            name: 'qwen-plus',
            label: 'Qwen Plus',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 16384,
            parameter_overrides: {
                max_tokens: {
                    maximum: 16384,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen3.5-flash.yaml',
        config: {
            name: 'qwen3.5-flash',
            label: 'Qwen3.5-Flash',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/bmp',
                'image/jpeg',
                'image/png',
                'image/tiff',
                'image/webp',
                'image/heic',
                'video/mp4',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
                thinking_budget: {
                    maximum: 81920,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen3.5-omni-plus.yaml',
        config: {
            name: 'qwen3.5-omni-plus',
            label: 'Qwen3.5-Omni-Plus',
            status: 'active',
            input_types: [
                'text/plain',
                'image/bmp',
                'image/jpeg',
                'image/png',
                'image/tiff',
                'image/webp',
                'image/heic',
                'audio/mp3',
                'audio/wav',
                'audio/flac',
                'video/mp4',
            ],
            output_types: ['text/plain', 'application/x-thinking', 'audio/wav'],
            context_size: 262144,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
                voice: {
                    default: 'Tina',
                    enum: ['Tina', 'Cherry', 'Ethan', 'Serena', 'Chelsie', 'Cindy'],
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen3.5-plus.yaml',
        config: {
            name: 'qwen3.5-plus',
            label: 'Qwen3.5-Plus',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/bmp',
                'image/jpeg',
                'image/png',
                'image/tiff',
                'image/webp',
                'image/heic',
                'video/mp4',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen3.6-flash.yaml',
        config: {
            name: 'qwen3.6-flash',
            label: 'Qwen3.6-Flash',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/bmp',
                'image/jpeg',
                'image/png',
                'image/tiff',
                'image/webp',
                'image/heic',
                'video/mp4',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
                thinking_budget: {
                    maximum: 131072,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen3.6-max-preview.yaml',
        config: {
            name: 'qwen3.6-max-preview',
            label: 'Qwen3.6-Max-Preview',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 240000,
            output_size: 64000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 64000,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen3.6-plus.yaml',
        config: {
            name: 'qwen3.6-plus',
            label: 'Qwen3.6-Plus',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/bmp',
                'image/jpeg',
                'image/png',
                'image/tiff',
                'image/webp',
                'image/heic',
                'video/mp4',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen3.7-flash.yaml',
        config: {
            name: 'qwen3.7-flash',
            label: 'Qwen3.7-Flash',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/bmp',
                'image/jpeg',
                'image/png',
                'image/tiff',
                'image/webp',
                'image/heic',
                'video/mp4',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 131072,
            parameter_overrides: {
                max_tokens: {
                    maximum: 131072,
                },
                thinking_budget: {
                    maximum: 262144,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen3.7-max.yaml',
        config: {
            name: 'qwen3.7-max',
            label: 'Qwen Max 3.7',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen3.7-plus.yaml',
        config: {
            name: 'qwen3.7-plus',
            label: 'Qwen3.7-Plus',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/bmp',
                'image/jpeg',
                'image/png',
                'image/tiff',
                'image/webp',
                'image/heic',
                'video/mp4',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/model/_dashscope/_models/qwen3.8-max.yaml',
        config: {
            name: 'qwen3.8-max',
            label: 'Qwen3.8-Max',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/bmp',
                'image/jpeg',
                'image/png',
                'image/tiff',
                'image/webp',
                'image/heic',
                'video/mp4',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 131072,
            parameter_overrides: {
                max_tokens: {
                    maximum: 131072,
                },
                thinking_budget: {
                    maximum: 262144,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'deepseek',
        sourcePath: 'src/agentscope/model/_deepseek/_models/deepseek-chat.yaml',
        config: {
            name: 'deepseek-chat',
            label: 'DeepSeek Chat',
            status: 'sunset',
            deprecated_at: '2026-07-24T00:00:00',
            input_types: ['text/plain'],
            output_types: ['text/plain'],
            context_size: 1000000,
            output_size: 384000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 384000,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'deepseek',
        sourcePath: 'src/agentscope/model/_deepseek/_models/deepseek-reasoner.yaml',
        config: {
            name: 'deepseek-reasoner',
            label: 'DeepSeek Reasoner',
            status: 'sunset',
            deprecated_at: '2026-07-24T00:00:00',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 384000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 384000,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'deepseek',
        sourcePath: 'src/agentscope/model/_deepseek/_models/deepseek-v4-flash.yaml',
        config: {
            name: 'deepseek-v4-flash',
            label: 'DeepSeek V4 Flash',
            status: 'active',
            input_types: ['text/plain', 'application/x-thinking'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 384000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 384000,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'deepseek',
        sourcePath: 'src/agentscope/model/_deepseek/_models/deepseek-v4-pro.yaml',
        config: {
            name: 'deepseek-v4-pro',
            label: 'DeepSeek V4 Pro',
            status: 'active',
            input_types: ['text/plain', 'application/x-thinking'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 384000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 384000,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'gemini',
        sourcePath: 'src/agentscope/model/_gemini/_models/gemini-2.5-flash-lite.yaml',
        config: {
            name: 'gemini-2.5-flash-lite',
            label: 'Gemini 2.5 Flash-Lite',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'audio/mp3',
                'audio/wav',
                'video/mp4',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1048576,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'gemini',
        sourcePath: 'src/agentscope/model/_gemini/_models/gemini-2.5-flash.yaml',
        config: {
            name: 'gemini-2.5-flash',
            label: 'Gemini 2.5 Flash',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
                'audio/mp3',
                'audio/wav',
                'video/mp4',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1048576,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'gemini',
        sourcePath: 'src/agentscope/model/_gemini/_models/gemini-2.5-pro.yaml',
        config: {
            name: 'gemini-2.5-pro',
            label: 'Gemini 2.5 Pro',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
                'audio/mp3',
                'audio/wav',
                'video/mp4',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1048576,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'gemini',
        sourcePath: 'src/agentscope/model/_gemini/_models/gemini-3-flash-preview.yaml',
        config: {
            name: 'gemini-3-flash-preview',
            label: 'Gemini 3 Flash Preview',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'audio/mp3',
                'audio/wav',
                'video/mp4',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1048576,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'gemini',
        sourcePath: 'src/agentscope/model/_gemini/_models/gemini-3.1-flash-lite.yaml',
        config: {
            name: 'gemini-3.1-flash-lite',
            label: 'Gemini 3.1 Flash-Lite',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'audio/mp3',
                'audio/wav',
                'video/mp4',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1048576,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'gemini',
        sourcePath: 'src/agentscope/model/_gemini/_models/gemini-3.1-pro-preview.yaml',
        config: {
            name: 'gemini-3.1-pro-preview',
            label: 'Gemini 3.1 Pro Preview',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'audio/mp3',
                'audio/wav',
                'video/mp4',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1048576,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'gemini',
        sourcePath: 'src/agentscope/model/_gemini/_models/gemini-3.5-flash-lite.yaml',
        config: {
            name: 'gemini-3.5-flash-lite',
            label: 'Gemini 3.5 Flash-Lite',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'audio/mp3',
                'audio/wav',
                'video/mp4',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1048576,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'gemini',
        sourcePath: 'src/agentscope/model/_gemini/_models/gemini-3.5-flash.yaml',
        config: {
            name: 'gemini-3.5-flash',
            label: 'Gemini 3.5 Flash',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'audio/mp3',
                'audio/wav',
                'video/mp4',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1048576,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'gemini',
        sourcePath: 'src/agentscope/model/_gemini/_models/gemini-3.6-flash.yaml',
        config: {
            name: 'gemini-3.6-flash',
            label: 'Gemini 3.6 Flash',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'audio/mp3',
                'audio/wav',
                'video/mp4',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1048576,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'moonshot',
        sourcePath: 'src/agentscope/model/_moonshot/_models/kimi-k2.5.yaml',
        config: {
            name: 'kimi-k2.5',
            label: 'Kimi K2.5',
            status: 'deprecated',
            deprecated_at: '2026-08-31T00:00:00',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 262144,
            output_size: 65536,
            parameter_overrides: {
                max_tokens: {
                    maximum: 65536,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'moonshot',
        sourcePath: 'src/agentscope/model/_moonshot/_models/kimi-k2.6.yaml',
        config: {
            name: 'kimi-k2.6',
            label: 'Kimi K2.6',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'video/mp4',
                'video/mpeg',
                'video/quicktime',
                'video/avi',
                'video/webm',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 262144,
            output_size: 32768,
            parameter_overrides: {
                max_tokens: {
                    maximum: 32768,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'moonshot',
        sourcePath: 'src/agentscope/model/_moonshot/_models/kimi-k2.7-code-highspeed.yaml',
        config: {
            name: 'kimi-k2.7-code-highspeed',
            label: 'Kimi K2.7 Code Highspeed',
            status: 'active',
            input_types: ['text/plain', 'application/x-thinking'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 262144,
            output_size: 32768,
            parameter_overrides: {
                max_tokens: {
                    maximum: 32768,
                },
                thinking_enable: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'moonshot',
        sourcePath: 'src/agentscope/model/_moonshot/_models/kimi-k2.7-code.yaml',
        config: {
            name: 'kimi-k2.7-code',
            label: 'Kimi K2.7 Code',
            status: 'active',
            input_types: ['text/plain', 'application/x-thinking'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 262144,
            output_size: 32768,
            parameter_overrides: {
                max_tokens: {
                    maximum: 32768,
                },
                thinking_enable: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'moonshot',
        sourcePath: 'src/agentscope/model/_moonshot/_models/kimi-k3.yaml',
        config: {
            name: 'kimi-k3',
            label: 'Kimi K3',
            status: 'active',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'video/mp4',
                'video/mpeg',
                'video/quicktime',
                'video/avi',
                'video/webm',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1048576,
            output_size: 1048576,
            parameter_overrides: {
                max_tokens: {
                    maximum: 1048576,
                },
                thinking_enable: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'moonshot',
        sourcePath: 'src/agentscope/model/_moonshot/_models/moonshot-v1-128k.yaml',
        config: {
            name: 'moonshot-v1-128k',
            label: 'Kimi Moonshot v1 128K',
            status: 'deprecated',
            deprecated_at: '2026-08-31T00:00:00',
            input_types: ['text/plain'],
            output_types: ['text/plain'],
            context_size: 131072,
            output_size: 131072,
            parameter_overrides: {
                max_tokens: {
                    maximum: 131072,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'moonshot',
        sourcePath: 'src/agentscope/model/_moonshot/_models/moonshot-v1-32k.yaml',
        config: {
            name: 'moonshot-v1-32k',
            label: 'Kimi Moonshot v1 32K',
            status: 'deprecated',
            deprecated_at: '2026-08-31T00:00:00',
            input_types: ['text/plain'],
            output_types: ['text/plain'],
            context_size: 32768,
            output_size: 32768,
            parameter_overrides: {
                max_tokens: {
                    maximum: 32768,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'moonshot',
        sourcePath: 'src/agentscope/model/_moonshot/_models/moonshot-v1-8k.yaml',
        config: {
            name: 'moonshot-v1-8k',
            label: 'Kimi Moonshot v1 8K',
            status: 'deprecated',
            deprecated_at: '2026-08-31T00:00:00',
            input_types: ['text/plain'],
            output_types: ['text/plain'],
            context_size: 8192,
            output_size: 8192,
            parameter_overrides: {
                max_tokens: {
                    maximum: 8192,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'ollama',
        sourcePath: 'src/agentscope/model/_ollama/_models/deepseek-r1-14b.yaml',
        config: {
            name: 'deepseek-r1:14b',
            label: 'DeepSeek R1 14B',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 131072,
            output_size: 8192,
            parameter_overrides: {
                max_tokens: {
                    maximum: 8192,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'ollama',
        sourcePath: 'src/agentscope/model/_ollama/_models/llama4.yaml',
        config: {
            name: 'llama4',
            label: 'Llama 4 Scout',
            status: 'active',
            input_types: ['text/plain', 'image/jpeg', 'image/png', 'image/gif', 'image/webp'],
            output_types: ['text/plain'],
            context_size: 10485760,
            output_size: 8192,
            parameter_overrides: {
                max_tokens: {
                    maximum: 8192,
                },
                thinking_enable: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'ollama',
        sourcePath: 'src/agentscope/model/_ollama/_models/qwen3-14b.yaml',
        config: {
            name: 'qwen3:14b',
            label: 'Qwen3 14B',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 40960,
            output_size: 8192,
            parameter_overrides: {
                max_tokens: {
                    maximum: 8192,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'ollama',
        sourcePath: 'src/agentscope/model/_ollama/_models/qwen3.5-9b.yaml',
        config: {
            name: 'qwen3.5',
            label: 'Qwen3.5 9B',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 262144,
            output_size: 8192,
            parameter_overrides: {
                max_tokens: {
                    maximum: 8192,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/gpt-4.1-mini.yaml',
        config: {
            name: 'gpt-4.1-mini',
            label: 'GPT-4.1 Mini',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1047576,
            output_size: 32768,
            parameter_overrides: {
                max_tokens: {
                    maximum: 32768,
                },
                thinking_enable: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/gpt-4.1-nano.yaml',
        config: {
            name: 'gpt-4.1-nano',
            label: 'GPT-4.1 Nano',
            status: 'deprecated',
            deprecated_at: '2026-10-23T00:00:00',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1047576,
            output_size: 32768,
            parameter_overrides: {
                max_tokens: {
                    maximum: 32768,
                },
                thinking_enable: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/gpt-4.1.yaml',
        config: {
            name: 'gpt-4.1',
            label: 'GPT-4.1',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1047576,
            output_size: 32768,
            parameter_overrides: {
                max_tokens: {
                    maximum: 32768,
                },
                thinking_enable: {
                    hidden: true,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/gpt-4o-mini.yaml',
        config: {
            name: 'gpt-4o-mini',
            label: 'GPT-4o Mini',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 128000,
            output_size: 16384,
            parameter_overrides: {
                max_tokens: {
                    maximum: 16384,
                },
                thinking_enable: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/gpt-4o.yaml',
        config: {
            name: 'gpt-4o',
            label: 'GPT-4o',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 128000,
            output_size: 16384,
            parameter_overrides: {
                max_tokens: {
                    maximum: 16384,
                },
                thinking_enable: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/gpt-5.4.yaml',
        config: {
            name: 'gpt-5.4',
            label: 'GPT-5.4',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1050000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/gpt-5.5.yaml',
        config: {
            name: 'gpt-5.5',
            label: 'GPT-5.5',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1050000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/gpt-5.6-luna.yaml',
        config: {
            name: 'gpt-5.6-luna',
            label: 'GPT-5.6 Luna',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1050000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/gpt-5.6-sol.yaml',
        config: {
            name: 'gpt-5.6-sol',
            label: 'GPT-5.6 Sol',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1050000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/gpt-5.6-terra.yaml',
        config: {
            name: 'gpt-5.6-terra',
            label: 'GPT-5.6 Terra',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1050000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/gpt-audio-mini.yaml',
        config: {
            name: 'gpt-audio-mini',
            label: 'GPT Audio Mini',
            status: 'deprecated',
            deprecated_at: '2027-01-20T00:00:00',
            input_types: ['text/plain', 'audio/wav', 'audio/mp3'],
            output_types: ['text/plain', 'audio/wav'],
            context_size: 128000,
            output_size: 16384,
            parameter_overrides: {
                max_tokens: {
                    maximum: 16384,
                },
                thinking_enable: {
                    hidden: true,
                },
                voice: {
                    default: 'alloy',
                    enum: ['alloy', 'echo', 'nova', 'shimmer', 'sage', 'verse'],
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/o3.yaml',
        config: {
            name: 'o3',
            label: 'o3',
            status: 'deprecated',
            deprecated_at: '2026-12-11T00:00:00',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 200000,
            output_size: 100000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 100000,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_chat',
        sourcePath: 'src/agentscope/model/_openai_chat/_models/o4-mini.yaml',
        config: {
            name: 'o4-mini',
            label: 'o4-mini',
            status: 'deprecated',
            deprecated_at: '2026-10-23T00:00:00',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 200000,
            output_size: 100000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 100000,
                },
                voice: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_response',
        sourcePath: 'src/agentscope/model/_openai_response/_models/gpt-4.1-mini.yaml',
        config: {
            name: 'gpt-4.1-mini',
            label: 'GPT-4.1 Mini',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1047576,
            output_size: 32768,
            parameter_overrides: {
                max_tokens: {
                    maximum: 32768,
                },
                thinking_enable: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_response',
        sourcePath: 'src/agentscope/model/_openai_response/_models/gpt-4.1-nano.yaml',
        config: {
            name: 'gpt-4.1-nano',
            label: 'GPT-4.1 Nano',
            status: 'deprecated',
            deprecated_at: '2026-10-23T00:00:00',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1047576,
            output_size: 32768,
            parameter_overrides: {
                max_tokens: {
                    maximum: 32768,
                },
                thinking_enable: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_response',
        sourcePath: 'src/agentscope/model/_openai_response/_models/gpt-4.1.yaml',
        config: {
            name: 'gpt-4.1',
            label: 'GPT-4.1',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1047576,
            output_size: 32768,
            parameter_overrides: {
                max_tokens: {
                    maximum: 32768,
                },
                thinking_enable: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_response',
        sourcePath: 'src/agentscope/model/_openai_response/_models/gpt-4o-mini.yaml',
        config: {
            name: 'gpt-4o-mini',
            label: 'GPT-4o Mini',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 128000,
            output_size: 16384,
            parameter_overrides: {
                max_tokens: {
                    maximum: 16384,
                },
                thinking_enable: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_response',
        sourcePath: 'src/agentscope/model/_openai_response/_models/gpt-4o.yaml',
        config: {
            name: 'gpt-4o',
            label: 'GPT-4o',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 128000,
            output_size: 16384,
            parameter_overrides: {
                max_tokens: {
                    maximum: 16384,
                },
                thinking_enable: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_response',
        sourcePath: 'src/agentscope/model/_openai_response/_models/gpt-5.4.yaml',
        config: {
            name: 'gpt-5.4',
            label: 'GPT-5.4 (Responses API)',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1050000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_response',
        sourcePath: 'src/agentscope/model/_openai_response/_models/gpt-5.5.yaml',
        config: {
            name: 'gpt-5.5',
            label: 'GPT-5.5',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1050000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_response',
        sourcePath: 'src/agentscope/model/_openai_response/_models/gpt-5.6-luna.yaml',
        config: {
            name: 'gpt-5.6-luna',
            label: 'GPT-5.6 Luna',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1050000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_response',
        sourcePath: 'src/agentscope/model/_openai_response/_models/gpt-5.6-sol.yaml',
        config: {
            name: 'gpt-5.6-sol',
            label: 'GPT-5.6 Sol',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1050000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_response',
        sourcePath: 'src/agentscope/model/_openai_response/_models/gpt-5.6-terra.yaml',
        config: {
            name: 'gpt-5.6-terra',
            label: 'GPT-5.6 Terra',
            status: 'active',
            input_types: [
                'text/plain',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain'],
            context_size: 1050000,
            output_size: 128000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 128000,
                },
                thinking_enable: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_response',
        sourcePath: 'src/agentscope/model/_openai_response/_models/o3.yaml',
        config: {
            name: 'o3',
            label: 'o3 (Responses API)',
            status: 'deprecated',
            deprecated_at: '2026-12-11T00:00:00',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 200000,
            output_size: 100000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 100000,
                },
                temperature: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'openai_response',
        sourcePath: 'src/agentscope/model/_openai_response/_models/o4-mini.yaml',
        config: {
            name: 'o4-mini',
            label: 'o4-mini (Responses API)',
            status: 'deprecated',
            deprecated_at: '2026-10-23T00:00:00',
            input_types: [
                'text/plain',
                'application/x-thinking',
                'image/jpeg',
                'image/png',
                'image/gif',
                'image/webp',
                'application/pdf',
            ],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 200000,
            output_size: 100000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 100000,
                },
                temperature: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'xai',
        sourcePath: 'src/agentscope/model/_xai/_models/grok-3-fast.yaml',
        config: {
            name: 'grok-3-fast',
            label: 'Grok 3 Fast',
            status: 'deprecated',
            input_types: ['text/plain', 'image/jpeg', 'image/png'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 131072,
            output_size: 16000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 16000,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'xai',
        sourcePath: 'src/agentscope/model/_xai/_models/grok-3-mini.yaml',
        config: {
            name: 'grok-3-mini',
            label: 'Grok 3 Mini',
            status: 'deprecated',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 131072,
            output_size: 16000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 16000,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'xai',
        sourcePath: 'src/agentscope/model/_xai/_models/grok-3.yaml',
        config: {
            name: 'grok-3',
            label: 'Grok 3',
            status: 'deprecated',
            input_types: ['text/plain', 'image/jpeg', 'image/png'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 131072,
            output_size: 16000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 16000,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'xai',
        sourcePath: 'src/agentscope/model/_xai/_models/grok-4.20-0309-non-reasoning.yaml',
        config: {
            name: 'grok-4.20-0309-non-reasoning',
            label: 'Grok 4.20 Non-Reasoning',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain'],
            context_size: 1000000,
            output_size: 64000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 64000,
                },
                thinking_enable: {
                    hidden: true,
                },
                reasoning_effort: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'xai',
        sourcePath: 'src/agentscope/model/_xai/_models/grok-4.20-0309-reasoning.yaml',
        config: {
            name: 'grok-4.20-0309-reasoning',
            label: 'Grok 4.20 Reasoning',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 64000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 64000,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'xai',
        sourcePath: 'src/agentscope/model/_xai/_models/grok-4.20-multi-agent-0309.yaml',
        config: {
            name: 'grok-4.20-multi-agent-0309',
            label: 'Grok 4.20 Multi-Agent',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 64000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 64000,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'xai',
        sourcePath: 'src/agentscope/model/_xai/_models/grok-4.3.yaml',
        config: {
            name: 'grok-4.3',
            label: 'Grok 4.3',
            status: 'active',
            input_types: ['text/plain', 'image/jpeg', 'image/png'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 1000000,
            output_size: 64000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 64000,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'xai',
        sourcePath: 'src/agentscope/model/_xai/_models/grok-4.5.yaml',
        config: {
            name: 'grok-4.5',
            label: 'Grok 4.5',
            status: 'active',
            input_types: ['text/plain', 'image/jpeg', 'image/png'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 500000,
            output_size: 32000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 32000,
                },
            },
        },
    },
    {
        kind: 'chat',
        provider: 'xai',
        sourcePath: 'src/agentscope/model/_xai/_models/grok-build-0.1.yaml',
        config: {
            name: 'grok-build-0.1',
            label: 'Grok Build 0.1',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['text/plain', 'application/x-thinking'],
            context_size: 256000,
            output_size: 16000,
            parameter_overrides: {
                max_tokens: {
                    maximum: 16000,
                },
            },
        },
    },
    {
        kind: 'tts',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/tts/_dashscope/_cosyvoice_models/cosyvoice-v3-flash.yaml',
        config: {
            name: 'cosyvoice-v3-flash',
            label: 'CosyVoice-v3-Flash',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['audio/wav'],
            voices: [
                'longanyang',
                'longanhuan',
                'longhuhu_v3',
                'longyingmu_v3',
                'longxiaochun_v3',
                'longxiaoxia_v3',
                'longlaotie_v3',
                'longshuo_v3',
                'longshu_v3',
            ],
            parameter_overrides: {},
        },
    },
    {
        kind: 'tts',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/tts/_dashscope/_cosyvoice_models/cosyvoice-v3-plus.yaml',
        config: {
            name: 'cosyvoice-v3-plus',
            label: 'CosyVoice-v3-Plus',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['audio/wav'],
            voices: ['longanyang', 'longanhuan'],
            parameter_overrides: {},
        },
    },
    {
        kind: 'tts',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/tts/_dashscope/_models/qwen3-tts-flash-realtime.yaml',
        config: {
            name: 'qwen3-tts-flash-realtime',
            label: 'Qwen3-TTS-Flash-Realtime',
            status: 'active',
            realtime: true,
            input_types: ['text/plain'],
            output_types: ['audio/wav'],
            voices: ['Cherry', 'Serena', 'Ethan', 'Chelsie'],
            parameter_overrides: {},
        },
    },
    {
        kind: 'tts',
        provider: 'dashscope',
        sourcePath: 'src/agentscope/tts/_dashscope/_models/qwen3-tts-flash.yaml',
        config: {
            name: 'qwen3-tts-flash',
            label: 'Qwen3-TTS-Flash',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['audio/wav'],
            voices: ['Cherry', 'Serena', 'Ethan', 'Chelsie'],
            parameter_overrides: {},
        },
    },
    {
        kind: 'tts',
        provider: 'gemini',
        sourcePath: 'src/agentscope/tts/_gemini/_models/gemini-2.5-flash-preview-tts.yaml',
        config: {
            name: 'gemini-2.5-flash-preview-tts',
            label: 'Gemini 2.5 Flash Preview TTS',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['audio/wav'],
            voices: [
                'Zephyr',
                'Puck',
                'Charon',
                'Kore',
                'Fenrir',
                'Leda',
                'Orus',
                'Aoede',
                'Callirrhoe',
                'Autonoe',
                'Enceladus',
                'Iapetus',
                'Umbriel',
                'Algieba',
                'Despina',
                'Erinome',
                'Algenib',
                'Rasalgethi',
                'Laomedeia',
                'Achernar',
                'Alnilam',
                'Schedar',
                'Gacrux',
                'Pulcherrima',
                'Achird',
                'Zubenelgenubi',
                'Vindemiatrix',
                'Sadachbia',
                'Sadaltager',
                'Sulafat',
            ],
            parameter_overrides: {},
        },
    },
    {
        kind: 'tts',
        provider: 'gemini',
        sourcePath: 'src/agentscope/tts/_gemini/_models/gemini-2.5-pro-preview-tts.yaml',
        config: {
            name: 'gemini-2.5-pro-preview-tts',
            label: 'Gemini 2.5 Pro Preview TTS',
            status: 'active',
            input_types: ['text/plain'],
            output_types: ['audio/wav'],
            voices: [
                'Zephyr',
                'Puck',
                'Charon',
                'Kore',
                'Fenrir',
                'Leda',
                'Orus',
                'Aoede',
                'Callirrhoe',
                'Autonoe',
                'Enceladus',
                'Iapetus',
                'Umbriel',
                'Algieba',
                'Despina',
                'Erinome',
                'Algenib',
                'Rasalgethi',
                'Laomedeia',
                'Achernar',
                'Alnilam',
                'Schedar',
                'Gacrux',
                'Pulcherrima',
                'Achird',
                'Zubenelgenubi',
                'Vindemiatrix',
                'Sadachbia',
                'Sadaltager',
                'Sulafat',
            ],
            parameter_overrides: {},
        },
    },
    {
        kind: 'tts',
        provider: 'openai',
        sourcePath: 'src/agentscope/tts/_openai/_models/gpt-4o-mini-tts.yaml',
        config: {
            name: 'gpt-4o-mini-tts',
            label: 'GPT-4o Mini TTS',
            status: 'active',
            input_types: ['text/plain'],
            output_types: [
                'audio/mpeg',
                'audio/opus',
                'audio/aac',
                'audio/flac',
                'audio/wav',
                'audio/pcm',
            ],
            voices: [
                'alloy',
                'ash',
                'ballad',
                'coral',
                'echo',
                'fable',
                'onyx',
                'nova',
                'sage',
                'shimmer',
                'verse',
            ],
            parameter_overrides: {},
        },
    },
    {
        kind: 'tts',
        provider: 'openai',
        sourcePath: 'src/agentscope/tts/_openai/_models/tts-1-hd.yaml',
        config: {
            name: 'tts-1-hd',
            label: 'TTS-1 HD',
            status: 'active',
            input_types: ['text/plain'],
            output_types: [
                'audio/mpeg',
                'audio/opus',
                'audio/aac',
                'audio/flac',
                'audio/wav',
                'audio/pcm',
            ],
            voices: [
                'alloy',
                'ash',
                'ballad',
                'coral',
                'echo',
                'fable',
                'onyx',
                'nova',
                'sage',
                'shimmer',
                'verse',
            ],
            parameter_overrides: {
                instructions: {
                    hidden: true,
                },
            },
        },
    },
    {
        kind: 'tts',
        provider: 'openai',
        sourcePath: 'src/agentscope/tts/_openai/_models/tts-1.yaml',
        config: {
            name: 'tts-1',
            label: 'TTS-1',
            status: 'active',
            input_types: ['text/plain'],
            output_types: [
                'audio/mpeg',
                'audio/opus',
                'audio/aac',
                'audio/flac',
                'audio/wav',
                'audio/pcm',
            ],
            voices: [
                'alloy',
                'ash',
                'ballad',
                'coral',
                'echo',
                'fable',
                'onyx',
                'nova',
                'sage',
                'shimmer',
                'verse',
            ],
            parameter_overrides: {
                instructions: {
                    hidden: true,
                },
            },
        },
    },
] as const satisfies readonly RawModelCardRecord[];
